### ISSUE TITLE
"Connection Strings only supported for Basic Auth type"

### ISSUE THREAD

**Issue by yorek** [microsoft/go-sqlcmd#296]
I get the error "Connection Strings only supported for Basic Auth type" when running ` sqlcmd config connection-strings`, even though the configuration is set to "basic":

```
version: v1
endpoints:
- asset:
    container:
      id: dc15e8783e30b4b8e4d06707bab18316ca55034c4b2f6d5b0499ec9c3d5703a7
      image: mcr.microsoft.com/mssql/server:latest
  endpoint:
    address: localhost
    port: 1433
  name: mssql
contexts:
- context:
    endpoint: mssql
    user: REDACTED@mssql
  name: mssql
currentcontext: mssql
users:
- name: REDACTED
  authentication-type: basic
  basic-auth:
    username: REDACTED
    password-encrypted: false
    password: REDACTED
```
